Web-CP2013-Zoo/config/routes.rb
WebCp2013Zoo::Application.routes.draw do

  resources :employees do
    resources :messages
  end

  resources :animals

  resources :home,  only: [:index]
  resources :zoo_setup_ui, only: [:index]

  resources :cages do
    resources :entrances do
      resources :doors do
      end
    end
  end

  root :to => 'home#index'

end

Web-CP2013-Zoo/app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :employee_id, :message

  belongs_to :employee
end

Web-CP2013-Zoo/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    @employee = Employee.find(params[:employee_id])
    @messages = @employee.messages

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])
    @employee = @message.employee

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @employee = Employee.find(params[:employee_id])

    @message = @employee.messages.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
    @employee = @message.employee
  end

  # POST /messages
  # POST /messages.json
  def create
    @employee = Employee.find(params[:employee_id])
    @message = @employee.messages.build(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to employee_message_path(@employee, @message), notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: employee_message_path(@employee, @message) }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])
    @employee = @message.employee

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to employee_message_path(@employee, @message), notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @employee = @message.employee
    @message.destroy

    respond_to do |format|
      format.html { redirect_to employee_messages_url(@employee) }
      format.json { head :no_content }
    end
  end
end

Web-CP2013-Zoo/app/helpers/messages_helper.rb
module MessagesHelper
end

Web-CP2013-Zoo/app/views/messages/_form.html.erb
<%= form_for([@employee,@message]) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :employee_id %><br />
    <%= f.number_field :employee_id %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Web-CP2013-Zoo/app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', employee_message_path(@employee, @message) %> |
<%= link_to 'Back', employee_messages_path(@employee) %>

Web-CP2013-Zoo/app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>Employee</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.employee_id %></td>
    <td><%= message.message %></td>
    <td><%= link_to 'Show', employee_message_path(@employee, message) %></td>
    <td><%= link_to 'Edit', edit_employee_message_path(@employee, message) %></td>
    <td><%= link_to 'Destroy', employee_message_path(@employee, message), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_employee_message_path(@employee) %>

Web-CP2013-Zoo/app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', employee_messages_path(@employee) %>

Web-CP2013-Zoo/app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Employee:</b>
  <%= @message.employee_id %>
</p>

<p>
  <b>Message:</b>
  <%= @message.message %>
</p>


<%= link_to 'Edit', edit_employee_message_path(@employee, @message) %> |
<%= link_to 'Back', employee_messages_path(@employee) %>