Web-CP2013-Zoo/config/routes.rb
WebCp2013Zoo::Application.routes.draw do

  resources :employees do
    resources :messages
  end

  resources :animals

  resources :home,  only: [:index]
  resources :zoo_setup_ui, only: [:index]

  resources :cages do
    resources :entrances do
      resources :doors do
      end
    end
  end

  root :to => 'home#index'

end

Web-CP2013-Zoo/app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :cage_id, :employee_id, :name
  belongs_to :cage
  has_many :messages, :dependent => :destroy
end

Web-CP2013-Zoo/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

Web-CP2013-Zoo/app/helpers/employees_helper.rb
module EmployeesHelper
end

Web-CP2013-Zoo/app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :employee_id %><br />
    <%= f.text_field :employee_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cage_id %><br />
    <%= f.number_field :cage_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Web-CP2013-Zoo/app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

Web-CP2013-Zoo/app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <tr>
    <th>Employee</th>
    <th>Name</th>
    <th>Cage</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.employee_id %></td>
    <td><%= employee.name %></td>
    <td><%= employee.cage_id %></td>
    <td><%= link_to 'Show', employee %></td>
    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
    <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Employee', new_employee_path %>

Web-CP2013-Zoo/app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

Web-CP2013-Zoo/app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Employee:</b>
  <%= @employee.employee_id %>
</p>

<p>
  <b>Name:</b>
  <%= @employee.name %>
</p>

<p>
  <b>Cage:</b>
  <%= @employee.cage_id %>
</p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>