Web-CP2013-Zoo/config/routes.rb
WebCp2013Zoo::Application.routes.draw do

  resources :employees do
    resources :messages
  end

  resources :animals

  resources :home,  only: [:index]
  resources :zoo_setup_ui, only: [:index]

  resources :cages do
    resources :entrances do
      resources :doors do
      end
    end
  end

  root :to => 'home#index'

end

Web-CP2013-Zoo/app/models/cage.rb
class Cage < ActiveRecord::Base
  attr_accessible :description, :name, :size, :category, :longitude, :latitude,
    :date_last_fed, :date_last_cleaned, :lights_on

  validates :name, :presence => true
  validates :name, :length => { :minimum => 1 }
  validates :size, :numericality => { :greater_than_or_equal_to => 5 }
  validates :longitude, :numericality => { :greater_than_or_equal_to => -180, :less_than_or_equal_to => 180 }
  validates :latitude,  :numericality => { :greater_than_or_equal_to => -90, :less_than_or_equal_to => 90 }

  has_many :entrances, :dependent => :destroy
  has_many :employees
  has_many :animals
end

Web-CP2013-Zoo/app/controllers/cages_controller.rb
class CagesController < ApplicationController
  # GET /cages
  # GET /cages.json
  def index
    @cages = Cage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cages }
    end
  end

  # GET /cages/1
  # GET /cages/1.json
  def show
    @cage = Cage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cage }
    end
  end

  # GET /cages/new
  # GET /cages/new.json
  def new
    @cage = Cage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cage }
    end
  end

  # GET /cages/1/edit
  def edit
    @cage = Cage.find(params[:id])
  end

  # POST /cages
  # POST /cages.json
  def create
    @cage = Cage.new(params[:cage])

    respond_to do |format|
      if @cage.save
        format.html { redirect_to cage_path(@cage), notice: 'Cage was successfully created.' }
        format.json { render json: @cage, status: :created, location: cage_path(@cage) }
      else
        format.html { render action: "new" }
        format.json { render json: @cage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cages/1
  # PUT /cages/1.json
  def update
    @cage = Cage.find(params[:id])

    respond_to do |format|
      if @cage.update_attributes(params[:cage])
        format.html { redirect_to cage_path(@cage), notice: 'Cage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cages/1
  # DELETE /cages/1.json
  def destroy
    @cage = Cage.find(params[:id])
    @cage.destroy

    respond_to do |format|
      format.html { redirect_to cages_url }
      format.json { head :no_content }
    end
  end
end

Web-CP2013-Zoo/app/helpers/cages_helper.rb
module CagesHelper
end

Web-CP2013-Zoo/app/views/cages/_form.html.erb
<%= form_for([@cage]) do |f| %>
  <% if @cage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cage.errors.count, "error") %> prohibited this cage from being saved:</h2>

      <ul>
      <% @cage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Web-CP2013-Zoo/app/views/cages/edit.html.erb
<h1>Editing cage</h1>

<%= render 'form' %>

<%= link_to 'Show', cage_path(@cage) %> |
<%= link_to 'Back', cages_path %>

Web-CP2013-Zoo/app/views/cages/index.html.erb
<h1>Listing cages</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Size</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cages.each do |cage| %>
  <tr>
    <td><%= cage.name %></td>
    <td><%= cage.size %></td>
    <td><%= cage.category %></td>
    <td><%= link_to 'Show', cage_path(cage) %></td>
    <td><%= link_to 'Edit', edit_cage_path(cage, cage) %></td>
    <td><%= link_to 'Destroy', cage_path(cage), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cage', new_cage_path %>

Web-CP2013-Zoo/app/views/cages/new.html.erb
<h1>New cage</h1>

<%= render 'form' %>

<%= link_to 'Back', cages_path %>

Web-CP2013-Zoo/app/views/cages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @cage.name %>
</p>

<p>
  <b>Size:</b>
  <%= @cage.size %>
</p>

<p>
  <b>Category:</b>
  <%= @cage.category %>
</p>


<%= link_to 'Edit', edit_cage_path(@cage) %> |
<%= link_to 'Back', cages_path(@cage) %>