Web-CP2013-Zoo/config/routes.rb
WebCp2013Zoo::Application.routes.draw do

  resources :employees do
    resources :messages
  end

  resources :animals

  resources :home,  only: [:index]
  resources :zoo_setup_ui, only: [:index]

  resources :cages do
    resources :entrances do
      resources :doors do
      end
    end
  end

  root :to => 'home#index'

end

Web-CP2013-Zoo/app/models/entrance.rb
class Entrance < ActiveRecord::Base
  attr_accessible :cage_id

  belongs_to :cage
  has_many :doors, :dependent => :destroy

  # Is the entrance open
  def open?
    open = false

    # if any door is open, consider the entrance open
    self.doors.each do |door|
      if door.open?
        open = true
      end
    end

    open
  end
end

Web-CP2013-Zoo/app/controllers/entrances_controller.rb
class EntrancesController < ApplicationController
  # GET /entrances
  # GET /entrances.json
  def index
    @cage = Cage.find(params[:cage_id])
    @entrances = @cage.entrances

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entrances }
    end
  end

  # GET /entrances/1
  # GET /entrances/1.json
  def show
    @entrance = Entrance.find(params[:id])
    @cage = @entrance.cage

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entrance }
    end
  end

  # GET /entrances/new
  # GET /entrances/new.json
  def new
    @cage = Cage.find(params[:cage_id])

    @entrance = @cage.entrances.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entrance }
    end
  end

  # GET /entrances/1/edit
  def edit
    @entrance = Entrance.find(params[:id])
    @cage = @entrance.cage
  end

  # POST /entrances
  # POST /entrances.json
  def create
    @cage = Cage.find(params[:cage_id])
    @entrance = @cage.entrances.build(params[:entrance])

    respond_to do |format|
      if @entrance.save
        format.html { redirect_to cage_entrance_path(@cage, @entrance), notice: 'Entrance was successfully created.' }
        format.json { render json: @entrance, status: :created, location: cage_entrance_path(@cage, @entrance) }
      else
        format.html { render action: "new" }
        format.json { render json: @entrance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entrances/1
  # PUT /entrances/1.json
  def update
    @entrance = Entrance.find(params[:id])
    @cage = @entrance.cage

    respond_to do |format|
      if @entrance.update_attributes(params[:entrance])
        format.html { redirect_to cage_entrance_path(@cage, @entrance), notice: 'Entrance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entrance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entrances/1
  # DELETE /entrances/1.json
  def destroy
    @entrance = Entrance.find(params[:id])
    @cage = @entrance.cage
    @entrance.destroy

    respond_to do |format|
      format.html { redirect_to cage_entrances_url(@cage) }
      format.json { head :no_content }
    end
  end
end

Web-CP2013-Zoo/app/helpers/entrances_helper.rb
module EntrancesHelper
end

Web-CP2013-Zoo/app/views/entrances/_form.html.erb
<%= form_for([@cage, @entrance]) do |f| %>
  <% if @entrance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entrance.errors.count, "error") %> prohibited this entrance from being saved:</h2>

      <ul>
      <% @entrance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cage_id %><br />
    <%= f.number_field :cage_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Web-CP2013-Zoo/app/views/entrances/edit.html.erb
<h1>Editing entrance</h1>

<%= render 'form' %>

<%= link_to 'Show', cage_entrance_path(@cage, @entrance) %> |
<%= link_to 'Back', cage_entrances_path(@cage) %>

Web-CP2013-Zoo/app/views/entrances/index.html.erb
<h1>Listing entrances</h1>

<table>
  <tr>
    <th>Cage</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entrances.each do |entrance| %>
  <%
    cage = entrance.cage
  %>
  <tr>
    <td><%= entrance.cage_id %></td>
    <td><%= link_to 'Show', cage_entrance_path(cage, entrance) %></td>
    <td><%= link_to 'Edit', edit_cage_entrance_path(cage, entrance) %></td>
    <td><%= link_to 'Destroy', cage_entrance_path(cage, entrance), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entrance', new_cage_entrance_path(@cage) %>

Web-CP2013-Zoo/app/views/entrances/new.html.erb
<h1>New entrance</h1>

<%= render 'form' %>

<%= link_to 'Back', cage_entrances_path(@cage) %>

Web-CP2013-Zoo/app/views/entrances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cage:</b>
  <%= @entrance.cage_id %>
</p>


<%= link_to 'Edit', edit_cage_entrance_path(@cage, @entrance) %> |
<%= link_to 'Back', cage_entrances_path(@cage) %>